### ISSUE TITLE
template 

### ISSUE THREAD

**Issue by tvld** [CorentinAndre/Vuejs-snippets#6]
Should we not use data *function* in template now?
```html
<template>
  <div id="">

  </div>
</template>
<script>
  export default {
    name: "",
    data: function () {
      return {
        // variable : value
      }
    }
  }
</script>
<style lang="scss" scoped>
</style>
```

**Comment by CorentinAndre** [comment]
Hi, 

I'm using es6 arrow function so it is a function. You can have a look about how to use it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)

**Comment by tvld** [comment]
Oops ... sorry I overlooked your "=>"  ;) Thanks
